# @license Apache-2.0
#
# Copyright 2024 8 Hobbies, LLC <hong@8hobbies.com>
#
# Licensed under the Apache License, Version 2.0(the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build and Deploy Pages

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  DIST_ROOT_DIR: _site/dists/latest

jobs:
  build:
    name: Build Pages
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Create the dist root directory
        run: |
          mkdir -p ${DIST_ROOT_DIR}

      - name: Download latest Hugo
        run: scripts/download_latest_hugo_deb.sh

      - name: Generate Debian Repo files
        run: scripts/generate_repo_files.sh

      - name: Configuring signing key
        run: gpg --import <<< "${{ secrets.SIGNING_KEY }}"

      - name: Sign Release
        run: |
          gpg -u 'Hugo APT Repo 8 Hobbies Signing Bot <contact@8hob.io>' -a -s --clearsign --output ${DIST_ROOT_DIR}/InRelease ${DIST_ROOT_DIR}/Release

      - name: Make Public Key available
        run: mv signing-key _site/

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: _site

  test:
    name: Test the Repo
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'ubuntu-22.04']
    runs-on: ${{ matrix.os }}
    needs: build

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - uses: actions/download-artifact@v4
      - name: Uncompress Artifact
        run: |
          tar xvf github-pages/artifact.tar
          rm github-pages/artifact.tar
          rmdir github-pages

      - name: Ensure no Hugo Package in Default Repo
        run: |
          sudo rm /etc/apt/sources.list
          sudo rm -f /etc/apt/sources.list.d/*
          sudo apt-get update
          ! apt-cache show hugo
      - name: Ensure no Hugo installed
        run: |
          ! type hugo

      - name: Add the APT Repo
        run: echo "deb [signed-by=/etc/apt/keyrings/hugo.gpg] http://localhost:9000 latest main" | sudo tee /etc/apt/sources.list.d/hugo.list
      - name: Trust the Key
        run: sudo cp ${PWD}/signing-key /etc/apt/keyrings/hugo.gpg

      - name: Install Hugo
        run: |
          python -m http.server 9000 &
          while ! nc -z localhost 9000; do
              sleep 0.5
          done
          sudo apt-get update
          sudo apt-get install -y hugo
      - name: Test running Hugo
        run: hugo version

  deploy:
    name: Deploy Pages
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: [build, test]
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
